In [1]:
import numpy as np

In [4]:
a = np.arange(5)
b = np.arange(5,10)
c = np.arange(10,15)
print(a)
print(b)

[0 1 2 3 4]
[5 6 7 8 9]


In [5]:
x = np.vstack([a,b])
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
x = np.vstack([x,c])
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
